const USER_ROLES = {
  PARTICIPANT: "PARTICIPANT",
  JUDGE: "JUDGE",
  ORGANIZER: "ORGANIZER",
  COMPANY: "COMPANY",
  SUPER_ADMIN: "SUPER_ADMIN",
};

const HACKATHON_STATUS = {
  UPCOMING: "UPCOMING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
};

module.exports = {
  USER_ROLES,
  HACKATHON_STATUS,
};
